package org.example.rideshareapp.controllers;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import org.example.rideshareapp.Main;

import java.io.IOException;

/**
 * Controller responsible for handling user login operations within the
 * RideShare application. This includes validating login credentials, loading
 * the appropriate interface based on user classification, and opening the
 * sign-up window when requested.
 */
public class LoginController {

    /** Entry field for typing the username. */
    @FXML private TextField usernameField;

    /** Entry field for typing the account password. */
    @FXML private PasswordField passwordField;

    /** Label used to display login status or error messages. */
    @FXML private Label statusLabel;

    /** Entry field for typing the user classification. */
    @FXML private TextField classField;

    /** Reference to the main application for window switching. */
    private Main mainApp;

    /**
     * Injects the main application instance into the controller so that it can
     * request UI transitions such as opening the sign-up window.
     *
     * @param mainApp the main application instance
     */
    public void setMainApp(Main mainApp) {
        this.mainApp = mainApp;
    }

    /**
     * @return the text currently entered in the username field
     */
    public String getUsername() { return usernameField.getText(); }

    /**
     * @return the text currently entered in the password field
     */
    public String getPassword() { return passwordField.getText(); }

    /**
     * @return the text currently entered in the classification field
     */
    public String getClassification() { return classField.getText(); }

    /**
     * Triggered when the user presses the Login button. Validates credentials
     * using the application's shared {@code ProfileService} instance and, if
     * valid, loads the appropriate interface for the user's classification.
     *
     * @param event the action event generated by clicking the login button
     */
    @FXML
    private void onLogin(ActionEvent event) {
        statusLabel.setText("");

        String username = (usernameField.getText() == null) ? "" : usernameField.getText().trim();
        String password = (passwordField.getText() == null) ? "" : passwordField.getText().trim();
        String classification = (classField.getText() == null) ? "" : classField.getText().trim();

        if (username.isEmpty() || password.isEmpty() || classification.isEmpty()) {
            statusLabel.setText("Please enter username, password, and classification.");
            return;
        }

        boolean ok = Main.PROFILE_SERVICE.login(username, password, classification);

        if (!ok) {
            statusLabel.setText("Invalid credentials.");
            return;
        }

        System.out.println("[Login] User '" + username + "' logged in successfully.");
        System.out.println("[DEBUG] Logged-in user ID = " + Main.PROFILE_SERVICE.getProfileId());

        Stage window = (Stage) statusLabel.getScene().getWindow();

        try {
            FXMLLoader loader;

            if (classification.equalsIgnoreCase("Driver")) {
                loader = new FXMLLoader(
                        getClass().getResource("/org/example/rideshareapp/DriverPage.fxml")
                );
            } else if (classification.equalsIgnoreCase("Rider")) {
                loader = new FXMLLoader(
                        getClass().getResource("/org/example/rideshareapp/main.fxml")
                );
            } else {
                statusLabel.setText("Invalid classification input.");
                return;
            }

            javafx.scene.Parent root = loader.load();
            javafx.scene.Scene scene = new javafx.scene.Scene(root);
            window.setScene(scene);
            window.show();

        } catch (IOException e) {
            e.printStackTrace();
            statusLabel.setText("Failed to load UI: " + e.getMessage());
        }
    }

    /**
     * Triggered when the user clicks the Sign-Up button. Requests that the
     * main application load the sign-up interface.
     */
    @FXML
    private void onSignup() {
        statusLabel.setText("");

        try {
            if (mainApp != null) {
                mainApp.showSignup();
            } else {
                System.err.println("[Login] mainApp is null in onSignup().");
            }
        } catch (Exception e) {
            e.printStackTrace();
            statusLabel.setText("Unable to open Sign Up.");
        }
    }
}
